### ISSUE TITLE
version.dll and dmitriRender.dat

### ISSUE THREAD

**Issue by TishSerg** [GDaily/dmitriRender.dat---NVIDIA-#2]
Hi. Sorry for asking here, but could you please explain in README.md what is `Watermark/*/version.dll` exactly does?

Same question for the `dmitriRender.dat` files under different dirs...

**Comment by GDaily** [comment]
version.dll can hide trial version logo

dmitriRender.dat can fix green screen bug 

i just collect these files , not developer

**Comment by TishSerg** [comment]
I tried to copy `version.dll` to PotPlayer dir. With that file PotPlayer doesn't start :(

I saw somewhere, to fix PotPlayer start with `version.dll` I have to uninstall some Windows update. But I didn't find that update on my machine:
```
Microsoft Windows [Version 10.0.19043.1052]
(c) Корпорація Майкрософт. Усі права захищені.

C:\Users\Serg> wmic qfe list
Caption                                     CSName  Description      FixComments  HotFixID   InstallDate  InstalledBy          InstalledOn  Name  ServicePackInEffect  Status
http://support.microsoft.com/?kbid=5003254  THOR    Update                        KB5003254               NT AUTHORITY\SYSTEM  5/28/2021
http://support.microsoft.com/?kbid=5003537  THOR    Update                        KB5003537
https://support.microsoft.com/help/5000736  THOR    Update                        KB5000736                                    4/9/2021
https://support.microsoft.com/help/5003637  THOR    Security Update               KB5003637               NT AUTHORITY\SYSTEM  6/10/2021
                                            THOR    Security Update               KB5003742               NT AUTHORITY\SYSTEM  7/1/2021


C:\Users\Serg>
```

**Comment by GDaily** [comment]
the old version only can work on before windows 10 19041 

i update a new vesion  and test on 19042 work fine

i think it also can work on 19043

**Comment by TishSerg** [comment]
Wow! Updated `version.dll` worked on PotPlayer 210428 (1.7.21486) @ Windows 10 21H1 (build 19043.1081).
Big thanks!!!
BTW, where did you find that new `version.dll`?

**Comment by GDaily** [comment]
the developer release address ↓
https://www.chinapyg.com/thread-138928-1-1.html

**Comment by TishSerg** [comment]
> https://www.chinapyg.com/thread-138928-1-1.html

Unfortunately I cannot see any download links there. Likely it's because I'm not member on that site and I cannot sign in. Ok, no problem. I'll be happy to download from your repo here ;)

Thank you
Have a nice day
